### PR TITLE
CI to UPM branch

### PR DESCRIPTION
**Pull request by Hermesiss**
Added project for convenient edition
Added travis-ci.org integration
Added setup instructions to README.md
Changed com.vladfaust.unitywakatime.asmdef to editor only

### CODE REVIEW

**Comment by Hermesiss** [comment]
This CI will push changes to branch `upm` (will be created in process), so users could use it in UPM without downloading files as described [here](https://docs.unity3d.com/Manual/upm-dependencies.html#Git). You can skip ci if it's not necessary by adding `[skip ci]` in comment message.

I'm using this in my work, e.g. https://github.com/Hermesiss/unity-splines

I've tested it in my fork, in editor and build mode (no errors)

Before merging you need to:
1. Sign up at [Travis Ci](https://travis-ci.org/)
1. Enable this project there
1. Generate [github access token](https://github.com/settings/tokens)  with all repo scopes
1. Add this token to Environment Variables in [settings](https://travis-ci.org/vladfaust/unity-wakatime/settings)

**Comment by vladfaust** [comment]
Hello again, @Hermesiss!

You're saying that you're adding a project for "convenient" editing. That means that a developer which wants to modify this repo could have got a ready-to-go Unity project. And they could skip creating a new project explicitly. Am I right? If so, I can say that it's a positive change, but it should be done in a separate pull request (or, at least, commit).

I also don't understand why you'd want another branch. Isn't UPM happy with master?

**Comment by Hermesiss** [comment]
There's two difficulties if you want to use UPM with git:
1. Your files must be in root, not in subfolder (goodbye Unity project hierarchy)
1. All your files must have *.meta files (you need to open this project in Unity to generate them)

This is the perfect way to store files for UPM (I'm using it in my projects): https://github.com/Hermesiss/unity-wakatime/tree/upm-dev

Also, this is [how Unity works now](https://github.com/Unity-Technologies/2d-extras/tree/master) :)

I'm considering all proposed changes to be connected to each other, so it's one pull request

**Comment by Hermesiss** [comment]
More detailed info here https://github.com/Hermesiss/unity-package-manager-ci

**Comment by vladfaust** [comment]
I've reviewed everything. I don't see why we need to include `Project` dir. There is nothing related to it in https://github.com/Hermesiss/unity-wakatime/tree/upm-dev. I'd like to avoid having that monster in this repo.

Also I don't see any point in having separate `upm-dev` etc. branches. A single `package` branch deployed from master is enough IMO.

The `Installation` section in README should be reviewed more carefully. In your PR, there are some mistakes regarding to it.

In general, using UPM Git is good, but not for that price. The amount of files in this repository must be minimal. We should think of better implementation of it.

**Comment by Hermesiss** [comment]
1. Are you talking about `ProjectSettings` and `Packages` folders? Unity can open project with only `Assets` in it, yes. `Packages` with `manifest.json` will be mandatory as soon as you'll have dependencies (not our case right now). I can delete both folders, if you want
1. After receiving PR or while working in feature branch you want to test all processes, including working as UPM package. Separate `upm-test` branch is a way to do that without disturbing your users. If you want to let some of them test your beta, you can use `upm-dev` as well

**Comment by vladfaust** [comment]
Unity-Wakatime doesn't have any dependencies indeed and is not going too, I think. I intend to keep the repository as clean as possible, so please, reduce the amount of these files in this PR. Importing the project into a new Unity project each time to make some edits is fine. At least it's better than to store this monster meta and deps garbage in Git.

Regarding to `upm-*` branches — there is no need to test _package_ functionality. The act of converting the repo into package (which is, essentialy, some folder movements) should be _pure_ without any chances to affect the code logic. Therefore, the Travis CI script must be simplified. If possible, please, get rid of the CI folder and try to put everything into single `.travis.yml` file — if you have time. I could do it myself, too.

I'd like the branch to be called `package`, as it is used by the official Unity package you've mentioned above.

**Comment by Hermesiss** [comment]
You have no choice but to store meta files, they are essential to Unity. They have import settings and GUID that is used to refer to your scripts from scenes. And I repeat, every file and folder in `package` branch must have meta file

**Comment by vladfaust** [comment]
Well, I'm giving up. I can't make Travis CI work correctly. If you can fix it, go ahead :confused:

**Comment by Hermesiss** [comment]
If you add me as collaborator and [enable the repository](https://stackoverflow.com/questions/25857012/is-it-possible-to-set-up-travis-for-a-project-for-which-you-are-a-collaborator) in Travis I'll try to configure it

**Comment by vladfaust** [comment]
I've sent you an invite. Please not that I want the repo to be built on travis-ci.org, not travis-ci.com.

**Comment by Hermesiss** [comment]
I see, Travis is trying to build `master`, but there's no `travis.yml` yet. It should succeed after merging this PR to `master`.

**Comment by vladfaust** [comment]
Nope. I've tried to build the PR on travis-ci.com with github token, it failed as well. You can push a new branch, say, develop, and test it.

**Comment by vladfaust** [comment]
You didn't change a line of code, did you? :laughing:

**Comment by Hermesiss** [comment]
Only removed that strange manipulation with `GUTHUB_TOKEN`
PR-CI is working perfectly, just without deploying. And I've tested all this with my assets

**Comment by vladfaust** [comment]
Confirmed working both in 2018 and 2019. Awesome. Gonna merge tomorrow, as I'm sleeping now 😴

**Pull request merged**
